// <auto-generated />
namespace E_ProjectSem3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedbs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedbs));
        
        string IMigrationMetadata.Id
        {
            get { return "202003010152098_update-dbs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
