// <auto-generated />
namespace E_ProjectSem3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update555dư : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update555dư));
        
        string IMigrationMetadata.Id
        {
            get { return "202003031533598_update555dư"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
